name: Build Embedded Snapshots

on:
  push:
    branches: [main]
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        swift:
          - version: 6.3-snapshot-2026-02-26
            wasm-sdk-url: https://download.swift.org/swift-6.3-branch/wasm-sdk/swift-6.3-DEVELOPMENT-SNAPSHOT-2026-02-26-a/swift-6.3-DEVELOPMENT-SNAPSHOT-2026-02-26-a_wasm.artifactbundle.tar.gz
            wasm-sdk-checksum: 8ce66e881a4c88df6da9565a79b34060af930f661e7dd8d066f7f132b3eaf699
            wasm_sdk_id: swift-6.3-DEVELOPMENT-SNAPSHOT-2026-02-26-a_wasm-embedded

          - version: main-snapshot-2026-02-24
            wasm-sdk-url: https://download.swift.org/development/wasm-sdk/swift-DEVELOPMENT-SNAPSHOT-2026-02-24-a/swift-DEVELOPMENT-SNAPSHOT-2026-02-24-a_wasm.artifactbundle.tar.gz
            wasm-sdk-checksum: dc6e2fc24fb6cd7c7b72ef8d61dbfc3577bc1e360f33d410aebeda8974f1d02f
            wasm_sdk_id: swift-DEVELOPMENT-SNAPSHOT-2026-02-24-a_wasm-embedded
        examples:
          - Examples/Swiftle
          - Examples/Basic

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift.version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ${{ matrix.examples }}/pnpm-lock.yaml

      - name: Install Swift WASM SDK
        run: swift sdk install ${{ matrix.swift.wasm-sdk-url }} --checksum ${{ matrix.swift.wasm-sdk-checksum }}

      - name: Install dependencies
        working-directory: ${{ matrix.examples }}
        run: pnpm preinstall && pnpm install

      - name: Build
        working-directory: ${{ matrix.examples }}
        run: pnpm build
